### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by lao-ling-jie** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#16]
Thanks for your meaningful work!  I got into some trouble when I try to visualize the last stages’ convolution layer by Grad-CAM (like below).  If possible could you share with me a copy of the visualization code?  
![1](https://user-images.githubusercontent.com/50287419/99179768-9b8abc80-275b-11eb-9cf5-f0e2fca06e2c.jpg)

email: 1042745117@qq.com

**Comment by childrenadd** [comment]
> 
> 
> Thanks for your meaningful work! I got into some trouble when I try to visualize the last stages’ convolution layer by Grad-CAM (like below). If possible could you share with me a copy of the visualization code?
> ![1](https://user-images.githubusercontent.com/50287419/99179768-9b8abc80-275b-11eb-9cf5-f0e2fca06e2c.jpg)
> 
> email: [1042745117@qq.com](mailto:1042745117@qq.com)

Hello, did you implement this program? Does it have to be two Gpus？

**Comment by lao-ling-jie** [comment]
> > Thanks for your meaningful work! I got into some trouble when I try to visualize the last stages’ convolution layer by Grad-CAM (like below). If possible could you share with me a copy of the visualization code?
> > ![1](https://user-images.githubusercontent.com/50287419/99179768-9b8abc80-275b-11eb-9cf5-f0e2fca06e2c.jpg)
> > email: [1042745117@qq.com](mailto:1042745117@qq.com)
> 
> Hello, did you implement this program? Does it have to be two Gpus？
I implement it，but I just use one GPU

**Comment by hhkyhhxbc** [comment]
> Thanks for your meaningful work! I got into some trouble when I try to visualize the last stages’ convolution layer by Grad-CAM (like below). If possible could you share with me a copy of the visualization code?
> ![1](https://user-images.githubusercontent.com/50287419/99179768-9b8abc80-275b-11eb-9cf5-f0e2fca06e2c.jpg)
> 
> email: [1042745117@qq.com](mailto:1042745117@qq.com)

hello HXD,have u finished the visualize code ？ when i try to visualize the gradcam,I get in trouble coincidentally.Could u share your visualize code  If it's convenient，a big big big thank u

**Comment by lao-ling-jie** [comment]
> > Thanks for your meaningful work! I got into some trouble when I try to visualize the last stages’ convolution layer by Grad-CAM (like below). If possible could you share with me a copy of the visualization code?
> > ![1](https://user-images.githubusercontent.com/50287419/99179768-9b8abc80-275b-11eb-9cf5-f0e2fca06e2c.jpg)
> > email: [1042745117@qq.com](mailto:1042745117@qq.com)
> 
> hello HXD,have u finished the visualize code ？ when I try to visualize the gradcam,I get in trouble coincidentally.Could u share your visualize code If it's convenient，a big big big thank u

sorry, I didn't finish it

**Comment by hhkyhhxbc** [comment]
> > > Thanks for your meaningful work! I got into some trouble when I try to visualize the last stages’ convolution layer by Grad-CAM (like below). If possible could you share with me a copy of the visualization code?
> > > ![1](https://user-images.githubusercontent.com/50287419/99179768-9b8abc80-275b-11eb-9cf5-f0e2fca06e2c.jpg)
> > > email: [1042745117@qq.com](mailto:1042745117@qq.com)
> > 
> > 
> > hello HXD,have u finished the visualize code ？ when I try to visualize the gradcam,I get in trouble coincidentally.Could u share your visualize code If it's convenient，a big big big thank u
> 
> sorry, I didn't finish it

pity！I will keep trying

**Comment by lao-ling-jie** [comment]
> > > > Thanks for your meaningful work! I got into some trouble when I try to visualize the last stages’ convolution layer by Grad-CAM (like below). If possible could you share with me a copy of the visualization code?
> > > > ![1](https://user-images.githubusercontent.com/50287419/99179768-9b8abc80-275b-11eb-9cf5-f0e2fca06e2c.jpg)
> > > > email: [1042745117@qq.com](mailto:1042745117@qq.com)
> > > 
> > > 
> > > hello HXD,have u finished the visualize code ？ when I try to visualize the gradcam,I get in trouble coincidentally.Could u share your visualize code If it's convenient，a big big big thank u
> > 
> > 
> > sorry, I didn't finish it
> 
> pity！I will keep trying

I am h
