### ISSUE TITLE
如何使用训练好的模型去分类数据集？这里测试我遇到了一些问题。

### ISSUE THREAD

**Issue by ulanbator** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#17]
`# -*- coding:utf-8 -*-
# @time :2019.03.15
# @IDE : pycharm
# @author :lxztju
# @github : https://github.com/lxztju
from utils import test
import torch
import os
from PIL import Image
import pandas as pd
from tqdm import tqdm
import numpy as np
from collections import Counter
from torchvision import transforms, models

def predict(model):
    # 读入模型
    model = torch.load(trained_model)
    model.eval()
    print('..... Finished loading model! ......')
    ##将模型放置在gpu上运行
    if torch.cuda.is_available():
        model.cuda()
    pred_list, _id = [], []
    transform_test = transforms.Compose([
        transforms.Scale((550, 550)),
        transforms.CenterCrop(448),
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
    ])
    images = os.listdir(test_image_path)
    for image in tqdm(images):
        img_path = os.path.join(test_image_path, image)
        img = Image.open(img_path).convert('RGB')
        if torch.cuda.is_available():
            img = transform_test(img).unsqueeze(0).cuda()
        with torch.no_grad():
            _, _, _, output_concat = model(img)
        _, predicted = torch.max(output_concat.data, 1)
        print(img_path + predicted)

if __name__ == "__main__":
    trained_model = "./weight/model.pth"
    test_image_path = "/data/server77_data_b/fangzheng_crop"
    predict(trained_model) 
`

RuntimeError: running_mean should contain 16384 elements not 1024

**Comment by Wzj02200059** [comment]
i have meet the same question，did u solve ？

**Comment by Jiapeng-Ji** [comment]
这个模型对图像做了一个切割打乱的操作，在utils里面，‘utils.jigsaw_generator()’。你应该是没进行这一步，直接把图像输进去了，所以会报错。16384正好是1024的16倍，在train里面inputs应该为三张被切割的与一张原始图片正好4张，我推测应该是这个原因，你可以试一试。
