### ISSUE TITLE
关于t-sne可视化

### ISSUE THREAD

**Issue by MercuialC** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#18]
感谢您优秀的工作！
拜读了您的论文之后，有一些困惑想向您请教。
您论文中关于CUB鸟类的t-sne可视化图像
![image](https://user-images.githubusercontent.com/25022698/102592475-7a4c3000-414e-11eb-826a-808c1ee9b378.png)

1.我也尝试t-sne可视化cub最后一个卷积层输出的特征分布，但是tsne中每个点对应一个测试样本embedding的话，点显得比较稀疏，请问您的可视化结果中的每个点也是对应一个测试样本输入主干网络提取的最后一层卷积层的特征吗？
2.期待您分享t-sne可视化代码部分！能否分享一些t-sne绘图的技巧，比如类似您论文中t-sne聚类团分布。

非常感谢！祝： 研究工作顺利！

**Comment by RuoyiDu** [comment]
> 感谢您优秀的工作！
> 拜读了您的论文之后，有一些困惑想向您请教。
> 您论文中关于CUB鸟类的t-sne可视化图像
> ![image](https://user-images.githubusercontent.com/25022698/102592475-7a4c3000-414e-11eb-826a-808c1ee9b378.png)
> 
> 1.我也尝试t-sne可视化cub最后一个卷积层输出的特征分布，但是tsne中每个点对应一个测试样本embedding的话，点显得比较稀疏，请问您的可视化结果中的每个点也是对应一个测试样本输入主干网络提取的最后一层卷积层的特征吗？
> 2.期待您分享t-sne可视化代码部分！能否分享一些t-sne绘图的技巧，比如类似您论文中t-sne聚类团分布。
> 
> 非常感谢！祝： 研究工作顺利！

你提到的工作，应该是和这个repo相关的：https://github.com/PRIS-CV/Fine-Grained-or-Not
