### ISSUE TITLE
Result of inference convidence

### ISSUE THREAD

**Issue by Wzj02200059** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#19]
Thank you for awesome repo.
I want to get the convenience value of output，
so i print the ('output_concat.data',output_concat.data)
output_concat.data tensor([[ 0.6667,  2.4874, -0.2616, -0.8905, -1.0161, -1.3324,  0.9716, -3.1546,
          2.6772],
        [-1.0338, -2.5260,  0.4580,  0.6618,  1.2473,  1.4716, -0.4507,  2.6250,
         -2.7728]], device='cuda:0')
some of the confidence value is negative， and their sum is not 1.
wish ur reply

**Comment by IDayday** [comment]
I think negative value is normal phenomenon, if you want to get 1 as the sum, you could put your layer output into another softmax. This will work well.

**Comment by RuoyiDu** [comment]
> Thank you for awesome repo.
> I want to get the convenience value of output，
> so i print the ('output_concat.data',output_concat.data)
> output_concat.data tensor([[ 0.6667, 2.4874, -0.2616, -0.8905, -1.0161, -1.3324, 0.9716, -3.1546,
> 2.6772],
> [-1.0338, -2.5260, 0.4580, 0.6618, 1.2473, 1.4716, -0.4507, 2.6250,
> -2.7728]], device='cuda:0')
> some of the confidence value is negative， and their sum is not 1.
> wish ur reply

It's the result before softmax.
