### ISSUE TITLE
What does this function mean? "def jigsaw_generator(images, n)"

### ISSUE THREAD

**Issue by s-t-liu** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#20]
In utils.py ,line 42: def **jigsaw_generator(images, n)**.
What does this function mean?

**Comment by RuoyiDu** [comment]
> In utils.py ,line 42: def **jigsaw_generator(images, n)**.
> What does this function mean?

It shuffles the input image into jigsaw patches.
