### ISSUE TITLE
How can I train and test on a single gpu？

### ISSUE THREAD

**Issue by s-t-liu** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#21]
I noticed you used multiple GPUs to train. 
However, I Just have 1 GPU.  
**How can I train and test on a single GPU？**

**Comment by RuoyiDu** [comment]
> I noticed you used multiple GPUs to train.
> However, I Just have 1 GPU.
> **How can I train and test on a single GPU？**

The code "device = torch.device("cuda:0,1")" can work with only one GPU ID.
For example, "device = torch.device("cuda:0")".
