### ISSUE TITLE
关于gpu的问题

### ISSUE THREAD

**Issue by wcz1997** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#24]
# GPU
    device = torch.device("cuda:0,1")
    net.to(device)
# cudnn.benchmark = True
这里确定是net,而不是netp吗？还有为什么在python1.7中，“cuda:0,1"这样的写法不行？

**Comment by RuoyiDu** [comment]
> 

The code can be run without modification with pytorch=1.3.1. And a google search may provide an answer as to the impact of subsequent versions of pytorch.
