### ISSUE TITLE
advisory

### ISSUE THREAD

**Issue by gengyanlei** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#4]
Hello, author, have you tried other networks such as inceptionv3 as a backbone network?

**Comment by RuoyiDu** [comment]
> Hello, author, have you tried other networks such as inceptionv3 as a backbone network?

In order to compare with other sota methods we use VGG16 and ResNet50 as the backbone networks. Of course, the performance can be improved with more advanced backbone architecture.
