### ISSUE TITLE
Why should the size of patch be smaller than that of receptive field?

### ISSUE THREAD

**Issue by HeimingX** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#8]
Hi,

Thanks for the impressive research. 

I am a little bit confused about the content related to the choice of n in Sec 3.3: "the size of the patches should be smaller than the receptive field of the corresponding stage, otherwise, the performance of the jigsaw puzzle generator will be reduced". Could you please do a detailed explaination why this condition is required? Thanks a lot.

**Comment by RuoyiDu** [comment]
> Hi,
> Thanks for the impressive research.
> I am a little bit confused about the content related to the choice of n in Sec 3.3: "the size of the patches should be smaller than the receptive field of the corresponding stage, otherwise, the performance of the jigsaw puzzle generator will be reduced". Could you please do a detailed explaination why this condition is required? Thanks a lot.

It has been a common solution to solve FGVC tasks by extracting ﬁne-grained feature representations at local discriminative regions, since subtle details exhibit stability at local regions. When we restrict the size of jigsaw patches to be smaller than the network's receptive field, the network will be forced to mine discriminative features from smaller local parts than before.

**Comment by HeimingX** [comment]
> > Hi,
> > Thanks for the impressive research.
> > I am a little bit confused about the content related to the choice of n in Sec 3.3: "the size of the patches should be smaller than the receptive field of the corresponding stage, otherwise, the performance of the jigsaw puzzle generator will be reduced". Could you please do a detailed explaination why this condition is required? Thanks a lot.
> 
> It has been a common solution to solve FGVC tasks by extracting ﬁne-grained feature representations at local discriminative regions, since subtle details exhibit stability at local regions. When we restrict the size of jigsaw patches to be smaller than the network's receptive field, the network will be forced to mine discriminative features from smaller local parts than before.

Hi,

Thanks for your timely explaination.

Yes, the smaller jigsaw patch size will push network to learn more discriminative features from local regions. But I am still curious about the condition that why it requires the jigsaw patches to be smaller than the net's receptive field. Since if patch size > receptive field, the network will still be pushed to learn from local regions and it seems to to be more reasonable that most of the features are forced to be extracted from the inside area of patches. Could you give me more explanation to help me solve this puzzle? Thanks a lot.

**Comment by RuoyiDu** [comment]
> Hi,
> Thanks for the impressive research.
> I am a little bit confused about the content related to the choice of n in Sec 3.3: "the size of the patches should be smaller than the receptive field of the corresponding stage, otherwise, the performance of the jigsaw puzzle generator will be reduced". Could you please do a detailed explaination why this condition is required? Thanks a lot.
> 
> It has been a common solution to solve FGVC tasks by extracting ﬁne-grained feature representations at local discriminative regions, since subtle details exhibit stability at local regions. When we restrict the size of jigsaw patches to be smaller than the network's receptive field, the network will be forced to mine discriminative features from smaller local parts than before.
> 
> Hi,
> Thanks for your timely explaination.
> Yes, the smaller jigsaw patch size will push network to learn more discriminative features from local regions. But I am still curious about the condition that why it requires the jigsaw patches to be smaller than the net's receptive field. Since if patch size > receptive field, the network will still be pushed to learn from local regions and it seems to to be more reasonable that most of the features are forced to be extracted from the inside area of patches. Could you give me more explanation to help me solve this puzzle? Thanks a lot.

There are two advantages brought by jigsaw patch generator-processed images:
(1) Forcing the network to mine information of smaller granularities.
(2) Encouraging the network to learn more discriminative information.
If the patch size > receptive field, the advantage (1) will disapper, because the network cannot extract features from regions larger than its receptive filed. And it is just like training each stage with original images.

**Comment by HeimingX** [comment]
> > Hi,
> > Thanks for the impressive research.
> > I am a little bit confused about the content related to the choice of n in Sec 3.3: "the size of the patches should be smaller than the receptive field of the corresponding stage, otherwise, the performance of the jigsaw puzzle generator will be reduced". Could you please do a detailed explaination why this condition is required? Thanks a lot.
> > It has been a common solution to solve FGVC tasks by extracting ﬁne-grained feature representations at local discriminative regions, since subtle details exhibit stability at local regions. When we restrict the size of jigsaw patches to be smaller than the network's receptive field, the network will be forced to mine discriminative features from smaller local parts than before.
> > Hi,
> > Thanks for your timely explaination.
> > Yes, the smaller jigsaw patch size will push network to learn more discriminative features from local regions. But I am still curious about the condition that why it requires the jigsaw patches to be smaller than the net's receptive field. Since if patch size > receptive field, the network will still be pushed to learn from local regions and it seems to to be more reasonable that most of the features are forced to be extracted from the inside area of patches. Could you give me more explanation to help me solve this puzzle? Thanks a lot.
> 
> There are two advantages brought by jigsaw patch generator-processed images:
> (1) Forcing the network to mine information of smaller granularities.
> (2) Encouraging the network to learn more discriminative information.
> If the patch size > receptive field, the advantage (1) will disapper, because the network cannot extract features from regions larger than its receptive filed. And it is just like training each stage with original images.

Hi,

Thanks for your helpful explaination. 
Since the CNN filters are location invariant, the network training will not benefit from the jigsaw transformation for the patch size > receptive field case. Interesting. Thanks again.

Cheers
