### ISSUE TITLE
net setting

### ISSUE THREAD

**Issue by bolin12** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#9]
How can i get same scores in your paper , can you provide hyperparameters and net settings? thanks

**Comment by RuoyiDu** [comment]
> How can i get same scores in your paper , can you provide hyperparameters and net settings? thanks

The  same scores can be obtained with the provided codes, and you don't need to change any settings. Is there any problem when you run with the default settings in our code?

**Comment by RuoyiDu** [comment]
I notice you got accuracy of 84.06% with 20 epoches. I run with code from this repository without any changes and got accuracy of 85.07 with only 5 epoches just now. Maybe you could mail me at "beiyoudry@bupt.edu.cn", and we could talk more about the setting details. It is hard for me to find the problem with limited information.

**Comment by RuoyiDu** [comment]
> How can i get same scores in your paper , can you provide hyperparameters and net settings? thanks

I notice you got accuracy of 84.06% with 20 epoches. I run with code from this repository without any changes and got accuracy of 85.07% with only 5 epoches just now. Maybe you could mail me at "beiyoudry@bupt.edu.cn", and we can talk more about the setting details. It is hard for me to find the problem with limited information.
